---
- name: Deploy Cluster Manager Apps to searchheads
  hosts: searchheads
  become: yes
  become_user: splunk_user

  tasks:
    - name: Clone repository to /tmp
      git:
        repo: "https://github.com/layamba25/SplunkEngineerTraining"
        dest: "/tmp/SplunkEngineerTraining"
        clone: yes
        update: yes
    
    - name: Copy Search Head Configurations from /tmp to /opt/splunk/etc/apps directory
      shell: "cp -r /tmp/SplunkEngineerTraining/SplunkConfigurations/_SingleSite/IndexerClustering/TA-searchheads /opt/splunk/etc/apps/TA-searchheads"
    
    - name: Restart Splunk service with systemd
      systemd:
        name: Splunkd
        state: restarted
        sudo: yes
      # command: "sudo systemctl restart Splunkd"