---
- name: Deploy deploymentclient.conf to Splunk Universal Forwarder
  hosts: universalforwarder
  become: yes
  become_user: splunk_user
  

  tasks:
    - name: Clone repository
      git:
        repo: "https://github.com/layamba25/SplunkEngineerTraining"
        dest: "/tmp/SplunkEngineerTraining"
        clone: yes
        update: yes

    - name: Copy deploymentclient app to Splunk directory
      # copy:
      #   src: "/tmp/SplunkEngineerTraining/SplunkConfigurations/UniversalForwarder/ta-uf_dc"
      #   dest: "/opt/splunkforwarder/etc/apps/ta-uf_dc"
      #   owner: splunk_user
      #   group: splunk_user
      #   mode: '0644'
      shell: "cp -r /tmp/SplunkEngineerTraining/SplunkConfigurations/UniversalForwarder/ta-uf_dc /opt/splunkforwarder/etc/apps/"
      
    - name: Restart Splunk Forwarder service
      command: "/opt/splunkforwarder/bin/splunk restart"
