---
- name: Deploy deploymentclient.conf to Splunk Universal Forwarder
  hosts: deploymentserver
  become: yes

  tasks:
    - name: Ping all hosts
      ping:
      
    - name: Clone repository
      git:
        repo: "https://github.com/layamba25/SplunkEngineerTraining"
        dest: "/tmp/splunk_deploymentclient_conf"
        clone: yes
        update: yes

    - name: Copy deploymentclient.conf to Splunk directory
      copy:
        src: "/tmp/splunk_deploymentclient_conf/SplunkConfigurations/DeployementServer/deployment-apps"
        dest: "/opt/splunkforwarder/etc/deployment-apps"
        owner: splunk_user
        group: splunk_user
        mode: '0644'

    - name: Copy the serverclass.conf to the apps directory
      copy:
        src: "/tmp/splunk_deploymentclient_conf/SplunkConfigurations/DeployementServer/serverclass.conf"
        dest: "/opt/splunkforwarder/etc/apps"
        owner: splunk_user
        group: splunk_user
        mode: '0644'

    - name: Reload Deployment Server
      command: "/opt/splunk/bin/splunk reload deploy-server"