---
- name: Deploy deploymentclient.conf to Splunk Universal Forwarder
  hosts: universalforwarder
  become: yes
  become_user: splunk_user
  

  tasks:
    - name: Ping all hosts
      ping:
      
    - name: Clone repository
      git:
        repo: "https://github.com/layamba25/SplunkEngineerTraining"
        dest: "/tmp/splunk_deploymentclient_conf"
        clone: yes
        update: yes

    - name: Copy deploymentclient.conf to Splunk directory
      copy:
        src: "/tmp/splunk_deploymentclient_conf/SplunkConfigurations/UniversalForwarder/ta-uf_dc"
        dest: "/opt/splunkforwarder/etc/apps/ta-uf_dc"
        owner: splunk_user
        group: splunk_user
        mode: '0644'

    - name: Restart Splunk Forwarder service
      command: "/opt/splunkforwarder/bin/splunk restart"
