---
- name: Deploy deploymentclient.conf to Splunk Universal Forwarder
  hosts: indexers
  become: yes

  tasks:
    - name: Ping all hosts
      ping:
      
    - name: Clone repository
      git:
        repo: "https://github.com/layamba25/SplunkEngineerTraining"
        dest: "/tmp/splunk_deploymentclient_conf"
        clone: yes
        update: yes

    - name: Copy deploymentclient.conf to Splunk directory
      copy:
        src: "/tmp/splunk_deploymentclient_conf/SplunkConfigurations/EnvironmentTypes/Distributed/SingleSite/Splunk Universal Forwarder/deploymentclient.conf"
        dest: "/opt/splunkforwarder/etc/system/local/deploymentclient.conf"
        owner: splunk
        group: splunk
        mode: '0644'

    - name: Restart Splunk service
      command: "/opt/splunkforwarder/bin/splunk restart"
