version: '3'
services:
  awx:
    image: quay.io/ansible/awx:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - POSTGRES_USER=awx
      - POSTGRES_PASSWORD=awxpass
      - AWX_ADMIN_USER=admin
      - AWX_ADMIN_PASSWORD=adminpass
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
