name: Splunk Installer - Linux
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Splunk Installer
      run: |
        chmod +x ./BashScripts/splunk_installer.sh
        sudo -S /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
        sudo -S /opt/splunk/bin/splunk status
        sudo netstat -tuln | grep 8000
