name: Splunk Installer - Linux

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Splunk Installer
      run: |
        chmod +x Scripts/BashScripts/splunk_enterprise_installer.sh
        sudo Scripts/BashScripts/splunk_enterprise_installer.sh
        nc -zv 127.0.0.1 8000 && echo "Port 8000 is open" || echo "Port 8000 is closed"
